// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StepronEOP.Database;

#nullable disable

namespace StepHR365.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231006120038_initdb")]
    partial class initdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StepHR365.Model.CurrentPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeoTracking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportingTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WeekOff")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CurrentPosition");
                });

            modelBuilder.Entity("StepHR365.Model.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            DateCreated = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7572),
                            DateModified = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7574),
                            ModifiedBy = 1,
                            Name = "Administrative"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            DateCreated = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7576),
                            DateModified = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7577),
                            ModifiedBy = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            DateCreated = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7578),
                            DateModified = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7579),
                            ModifiedBy = 1,
                            Name = "Design"
                        });
                });

            modelBuilder.Entity("StepHR365.Model.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("From")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("StepHR365.Model.EducationCertificates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessionalDocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EducationCertificates");
                });

            modelBuilder.Entity("StepHR365.Model.EmployeeIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AadhaarNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameInAadhaar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameInPAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PANNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeeIdentity");
                });

            modelBuilder.Entity("StepHR365.Model.EmployeeInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionalMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeeInformation");
                });

            modelBuilder.Entity("StepHR365.Model.JoiningDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("JoinedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoticePeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProbationPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JoiningDetails");
                });

            modelBuilder.Entity("StepHR365.Model.LastThreeSalarySlips", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessionalDocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LastThreeSalarySlips");
                });

            modelBuilder.Entity("StepHR365.Model.PermanentAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PermanentAddress");
                });

            modelBuilder.Entity("StepHR365.Model.PersonalDocuments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AadharCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressProof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDProofPanCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecentPhotographs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PersonalDocuments");
                });

            modelBuilder.Entity("StepHR365.Model.PersonalInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PersonalInformation");
                });

            modelBuilder.Entity("StepHR365.Model.PresentAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PresentAddress");
                });

            modelBuilder.Entity("StepHR365.Model.ProfessionalDocuments", b =>
                {
                    b.Property<int?>("ProfessionalDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ProfessionalDocumentId"));

                    b.Property<string>("PreviousOrganizationAppointmentLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousOrganizationExperienceCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousOrganizationRelievingLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResignationTerminationLetter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfessionalDocumentId");

                    b.ToTable("ProfessionalDocuments");
                });

            modelBuilder.Entity("StepHR365.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportingManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            DateCreated = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7408),
                            DateModified = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7409),
                            DepartmentId = 1,
                            IsAdmin = true,
                            IsDeleted = false,
                            JoiningDate = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7405),
                            LastAccess = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7410),
                            ModifiedBy = 1,
                            Password = "Sanket@123",
                            ReportingManager = "manager1",
                            Status = true,
                            UserEmail = "stepron.sjoshi@gmail.com",
                            Username = "Sanket"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 1,
                            DateCreated = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7419),
                            DateModified = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7420),
                            DepartmentId = 1,
                            IsAdmin = true,
                            IsDeleted = false,
                            JoiningDate = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7416),
                            LastAccess = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7421),
                            ModifiedBy = 1,
                            Password = "Amol@123",
                            ReportingManager = "manager1",
                            Status = true,
                            UserEmail = "stepron.amolpatil@gmail.com",
                            Username = "Amol"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 1,
                            DateCreated = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7427),
                            DateModified = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7428),
                            DepartmentId = 1,
                            IsAdmin = true,
                            IsDeleted = false,
                            JoiningDate = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7425),
                            LastAccess = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7428),
                            ModifiedBy = 1,
                            Password = "Bhaveshree@123",
                            ReportingManager = "manager1",
                            Status = true,
                            UserEmail = "stepron.bshinde@gmail.com",
                            Username = "Bhaveshree"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 1,
                            DateCreated = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7434),
                            DateModified = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7435),
                            DepartmentId = 1,
                            IsAdmin = true,
                            IsDeleted = false,
                            JoiningDate = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7433),
                            LastAccess = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7436),
                            ModifiedBy = 1,
                            Password = "Sujit@123",
                            ReportingManager = "manager1",
                            Status = true,
                            UserEmail = "stepron.sgaikwad@gmail.com",
                            Username = "Sujit"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 1,
                            DateCreated = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7444),
                            DateModified = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7444),
                            DepartmentId = 1,
                            IsAdmin = true,
                            IsDeleted = false,
                            JoiningDate = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7442),
                            LastAccess = new DateTime(2023, 10, 6, 17, 30, 38, 444, DateTimeKind.Local).AddTicks(7445),
                            ModifiedBy = 1,
                            Password = "Pratteek@123",
                            ReportingManager = "manager1",
                            Status = true,
                            UserEmail = "stepron.pshauraya@gmail.com",
                            Username = "Pratteek"
                        });
                });

            modelBuilder.Entity("StepHR365.Model.Views.Departments_View1", b =>
                {
                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("Departments_View1", (string)null);
                });

            modelBuilder.Entity("StepHR365.Model.Views.User1_View1", b =>
                {
                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ReportingManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("User1_View1", (string)null);
                });

            modelBuilder.Entity("StepHR365.Model.Views.User_View1", b =>
                {
                    b.Property<string>("AadhaarNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AadharCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressProof")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("From")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeoTracking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDProofPanCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Institute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameInAadhaar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameInPAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoticePeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PANNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentPinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentPinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProbationPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionalMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecentPhotographs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportingManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportingTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime2");

                    b.Property<string>("WeekOff")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("User_View1", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
